### ISSUE TITLE
How to minimise on-disk database size?

### ISSUE THREAD

**Issue by r-m-harris** [maxmind/MaxMind-DB-Writer-perl#102]
I've been attempting to produce a cut-down version of the GeoLite2 database in order to reduce the on-disk size.  My approach has been to iterate over all nodes using MaxMind::DB::Reader and then selectively inserting each one into a new tree if it contains all of three fields in which I'm interested.  This works in so far as I do create a new database that seems to contain much terser records.  However, the new database is some 70 Mb in comparison to the 50 Mb of the original file.  I'd be grateful for some advice.  Here's my code:

```perl
#!/usr/bin/perl -w

use strict;
use warnings;
use Getopt::Std;
use MaxMind::DB::Reader;
use MaxMind::DB::Writer::Tree;
use Net::Works::Address;
use Net::Works::Network;

my %types = (
    city =>     'map',
    country =>  'map',
    names =>    'map',
    en =>       'utf8_string',
    iso_code => 'utf8_string'
);

my %options=();
getopts("i:o:", \%options);

if (!defined($options{i}) ||
    !defined($options{o})) {
	print "usage: $0 -i input_file -o ouput_file\n";
	exit 1;
}

my $reader = MaxMind::DB::Reader->new(file => $options{i});
open my $fh, '>:raw', $options{o};

my $writer = MaxMind::DB::Writer::Tree->new(
    {
        ip_version =>       $reader->metadata()->ip_version(),
        record_size =>      $reader->metadata()->record_size(),
        database_type =>    "Cut-down " . $reader->metadata()->database_type(),
        languages =>        ['en'],
        description =>      { en => $reader->metadata()->description()->{en} },
        map_key_type_callback => sub { $types{ $_[0] } },
        merge_strategy =>   'recurse',
    }
);

my @records;

$reader->iterate_search_tree(
	sub {
		my $ip_as_integer = shift;
		my $mask_length   = shift;
		my $data          = shift;
		my %record;
		my $add = 0;

		if ($data->{city}{names}{en}) {
			$record{data}{city}{names}{en} = $data->{city}{names}{en};
			$add++;
		}
		if ($data->{country}{names}{en}) {
			$record{data}{country}{names}{en} = $data->{country}{names}{en};
			$add++;
		}
		if ($data->{country}{iso_code}) {
			$add++;
			$record{data}{country}{iso_code} = $data->{country}{iso_code};
		}

		if ($add == 3) {
			$record{network} = {ip => $ip_as_integer, size => $mask_length};
			push @records, \%record;
		 }
	}
);

# Sorting here is a stab in the dark based on reading other issues.
foreach my $record (sort { $b->{network}{size} <=> $a->{network}{size} ||
                           $a->{network}{ip} <=> $b->{network}{ip} } @records) {
    my $address = Net::Works::Address->new_from_integer(
        integer => $record->{network}{ip});
    my $network = Net::Works::Network->new_from_string(
            string => $address->as_string . "/" . $record->{network}{size}
    );

    $writer->insert_network($network, $record->{data});
}

$writer->write_tree($fh);
close $fh;
```

**Comment by oschwald** [comment]
MaxMind databases have `alias_ipv6_to_ipv4` enabled. You will need to exclude the aliased ranges in order to see a size reduction as you are currently inserting them multiple times.

**Comment by r-m-harris** [comment]
> On 18 Dec 2018, at 22:22, Gregory Oschwald <notifications@github.com> wrote:
> 
> MaxMind databases have alias_ipv6_to_ipv4 enabled. You will need to exclude the aliased ranges in order to see a size reduction as you are currently inserting them multiple times.
> 
Many thanks for the reply.  Could you give me an example of what I would see from the iterator if I was passed an aliased range multiple times?  I don't quite understand the context.

Robert

**Comment by oschwald** [comment]
`::ffff:0:0/96`, `2001::/32`, and `2002::/16` are aliased to `::/96` in these databases. Unfortunately, I don't think there is a good way to tell this from the callbacks. You could just explicitly filter out subnets in these networks. Another option would be to use the CSV provided by MaxMind, which does not include them and would likely be faster.

**Comment by r-m-harris** [comment]
OK, but shouldn't I be able to effect the same aliasing in my new database by specifying alias_ipv6_to_ipv4 = 1 when constructing the writer?

**Comment by oschwald** [comment]
Yes, you can, but it won't let you insert into the aliased nodes, resulting in an exception. I suppose you could just catch all of those exceptions and ignore them given that it is just duplicate data.
