### ISSUE TITLE
Subnets are randomly dropped on merge

### ISSUE THREAD

**Issue by vszurma** [maxmind/MaxMind-DB-Writer-perl#104]
When adding a subnet which is part of a larger one, the former is dropped randomly.

I have attached two files, both created with the exact same code (also attached). In ca. 1/2 of the cases the smaller subnet is missing in the file:

![image](https://user-images.githubusercontent.com/4634937/55479636-d12e7080-561e-11e9-84ec-4175d725014c.png)

[example_code.zip](https://github.com/maxmind/MaxMind-DB-Writer-perl/files/3038642/example_code.zip)
[mmdbs.zip](https://github.com/maxmind/MaxMind-DB-Writer-perl/files/3038643/mmdbs.zip)

```
Perl Version: perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

```

**Comment by oschwald** [comment]
You are inserting into a binary tree. A bigger network will overwrite a smaller network. It appears "random" in your code as the order of the keys returned by `keys` is randomized by Perl.

**Comment by vszurma** [comment]
Acording to the [docs for insert_network](https://metacpan.org/pod/MaxMind::DB::Writer::Tree#Insert-Order,-Merging,-and-Overwriting) 

> Insert Order, Merging, and Overwriting
When merge_strategy is none, the last insert "wins". This means that if you insert 1.2.3.255/32 and then 1.2.3.0/24, the data for 1.2.3.255/24 will overwrite the data you previously inserted for 1.2.3.255/232. On the other hand, if you insert 1.2.3.255/32 last, then the tree will be split so that the 1.2.3.0 - 1.2.3.254 range has different data than 1.2.3.255.

>In this scenario, if you want to make sure that no data is overwritten then you need to sort your input by network prefix length.


Hash randomization was also my first guess but I do not know why the fact it is a binary three matters. 
The bahavior of the hashrefs changed in perl-5.18 so I think it worked as described in the first place. 

I know the "problem" of randomized maps/hashes from languages like go.
A quick fix could be to push the keys in correct order into an array and iterate through that array.

In my opionion being nondeterministic is a very bad option. This bug hit us in production - because it seems to work localy but failed in production.
