### ISSUE TITLE
allow private IP ranges in a custom maxminddb

### ISSUE THREAD

**Issue by darix** [maxmind/MaxMind-DB-Writer-perl#108]
use case:

internal networks might use e.g. 192.168/16 or 10/8 but still need to split the traffic by site.

with the old geoip based DB tools this was possible.

**Comment by darix** [comment]
also 127/8 would be nice for CI use cases.

**Comment by oschwald** [comment]
This is already possible. You can set `remove_reserved_networks` to false when creating the tree object.

**Comment by darix** [comment]
ah cool!

can you also create ASN dbs with the library?

**Comment by oschwald** [comment]
Yes.
