### ISSUE TITLE
Issue in insert network where raw string work but string in some variable does not work

### ISSUE THREAD

**Issue by jainabhi1** [maxmind/MaxMind-DB-Writer-perl#110]
use MaxMind::DB::Writer::Tree;
use strict;

my %types = (
    autonomous_system_number => 'int32',
    autonomous_system_organization  => 'utf8_string'
);

my $tree = MaxMind::DB::Writer::Tree->new(
    ip_version            => 4,
    record_size           => 32,
    database_type         => 'GeoLite2-ASN',
    languages             => ['en'],
    description           => { en => 'My database of IP data' },
    map_key_type_callback => sub { $types{ $_[0] } },
);

open(my $data, '<', "output.csv") or die;

while (my $line = <$data>)
{
    chomp $line;

    # Split the line and store it
    # inside the words array
    my @words = split ",", $line;

    my $ip = $words[0];
    print "$words[0], $words[1], $words[2] \n";
    $tree->insert_network(
            $ip ,
            {
                autonomous_system_number => 0 + $words[1],
                autonomous_system_organization => $words[2],
            },
    );
}

open my $fh, '>:raw', 'my-ip-data.mmdb';
$tree->write_tree($fh);

`~/git/Asn_test $ perl mmdb_asn_creater.pl
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LC_CTYPE = "en_IN.UTF-8",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
"1.0.0.0/24", "13335", "cloudflare" 
Argument "24"" isn't numeric in int at /Users/ajain/perl5/lib/perl5/darwin-thread-multi-2level/MaxMind/DB/Writer/Tree.pm line 197, <$data> line 1.
Invalid IP address: "1.0.0.0 at /Users/ajain/perl5/lib/perl5/darwin-thread-multi-2level/MaxMind/DB/Writer/Tree.pm line 206, <$data> line 1.
~/git/Asn_test $`

as you can see words[0] is "1.0.0.0/24" and it gives error but when i put "1.0.0.0/24" directly into insert network its works fine``

**Comment by oschwald** [comment]
It appears the value in your CSV are quoted. Perhaps use a CSV parser like `Text::CSV_XS`.
