### ISSUE TITLE
There is a problem when using map in map

### ISSUE THREAD

**Issue by ningliangquantil** [maxmind/MaxMind-DB-Writer-perl#114]
Hi：
    
![image](https://user-images.githubusercontent.com/52913618/93991412-d9eca680-fdbe-11ea-86af-e753e5fcb647.png)
I get an error when I use this format.
![image](https://user-images.githubusercontent.com/52913618/93991497-f7ba0b80-fdbe-11ea-85ec-92b5fe9f9033.png)

How should I fix this error.
Thanks very much！

**Comment by ningliangquantil** [comment]
I want this result:
![image](https://user-images.githubusercontent.com/52913618/94003233-8f265b00-fdcd-11ea-9bfe-61c3e5d35478.png)
But failed.
Need your help.
Thanks!

**Comment by oschwald** [comment]
`{ map => 'utf8' }` is invalid. Please see the [data types](https://metacpan.org/pod/MaxMind::DB::Writer::Tree#DATA-TYPES) documentation.

**Comment by ningliangquantil** [comment]
@oschwald , Thanks！
