### ISSUE TITLE
IPv4 and IPv6 data conflict

### ISSUE THREAD

**Issue by ningliangquantil** [maxmind/MaxMind-DB-Writer-perl#115]
Hi,

I found a problem when using both IPv4 and IPv6 generatethe ip2region.mmdb file: when the IPv4 segment is converted to IPv6, and the IPv6 also has this segment, it will cause problems in the result that the region information of IPv4 is overwritten by ipv6.

Than you.

**Comment by oschwald** [comment]
This is part of the file format. The range used for IPv4 is reserved so it should not be in use. The solution would be not to insert "IPv6" networks into that range.
