### ISSUE TITLE
The problem of ipv4 and ipv6 

### ISSUE THREAD

**Issue by ningliangquantil** [maxmind/MaxMind-DB-Writer-perl#116]
Hi, the IPv6 which were mapped in IPv4 IP segment are not written into the mmdb file, is it controlled by itself or there are related variables in the program that can be operated？
When IPv4 and IPv6 are in the same tree, what is default express way of the IPv4 in the program? Is it ::ffff:0:0/96?

Thanks

**Comment by oschwald** [comment]
I am not completely sure what you are asking, but the IPv4 range in an IPv6 file is at `::/96` and has aliases in several other places, including `::ffff:0:0/96` when `alias_ipv6_to_ipv4` is set to true.

**Comment by ningliangquantil** [comment]
I want IPv4 information not to be overwritten by IPv6 , when the IPv4 range in an IPv6 file.

**Comment by ningliangquantil** [comment]
@oschwald， I want IPv4 information not to be overwritten by IPv6 , when the IPv4 range in an IPv6 file.

**Comment by oschwald** [comment]
If you refrain from inserting into `::/96`, which is reserved anyway, there shouldn't be an issue of overwriting.

**Comment by ningliangquantil** [comment]
thanks
