### ISSUE TITLE
Search tree duplicated via Writer has much bigger size than an original

### ISSUE THREAD

**Issue by p01arbear** [maxmind/MaxMind-DB-Writer-perl#117]
Hello. 

I have a [test script](https://github.com/maxmind/MaxMind-DB-Writer-perl/files/6632769/read_write_test.pl.txt), which simply duplicates database via 
`iterate_search_tree() => Network->new_from_integer() => insert_network() => write_tree()`.

Script is runned inside docker, [Dockerfile](https://github.com/maxmind/MaxMind-DB-Writer-perl/files/6632870/Dockerfile.txt).

[This is a test GeoLite2-City.mmdb database](https://web.archive.org/web/20191227182209if_/https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz).

I can't understand why the file written by the `MaxMind::DB::Writer::Tree` has a 3.5x much bigger search tree size than the original.

Is something wrong in the script itself or the Perl Writer API has a bug?

**Comment by oschwald** [comment]
You are likely creating multiple copies of the IPv4 search tree. `alias_ipv6_to_ipv4` will use aliases instead, although you will likely end up with errors about inserting into aliased nodes. I don't think the Perl reader provides a way to skip aliased nodes. Personally, I would suggest looking at the Go reader and writer instead; it will also be much, much faster.
