### ISSUE TITLE
Could not determine the type for map key "color"

### ISSUE THREAD

**Issue by dukr** [maxmind/MaxMind-DB-Writer-perl#13]
When I try to run the example from your front page . 
## I got the error message: 

Could not determine the type for map key "color" lib/perl5/x86_64-linux-gnu-thread-multi/MaxMind/DB/Writer/Serializer.pm line 372.

**Comment by harlow** [comment]
For anyone running into the same error; it typically happens when the types for `map_key_type_callback` aren't defined. 

For example the `color` attribute could be defined as a string:

```perl
# define metadata types that will be stored with IP range
my %types = (
  color => 'utf8_string',
);

# create new Tree
my $tree = MaxMind::DB::Writer::Tree->new(
  map_key_type_callback => sub { $types{ $_[0] } },
  # ...
);
```
