### ISSUE TITLE
Adding net ranges without CIDR notation

### ISSUE THREAD

**Issue by coderholic** [maxmind/MaxMind-DB-Writer-perl#31]
All of the examples use CIDR notation when adding network ranges, eg:

```
my $network = Net::Works::Network->new_from_string( string => '8.23.0.0/16' );
```

It is possible to provide a start and end IP instead? For example, I'd like to be able to do something like:

```
my $network = Net::Works::Network->new_from_string( start => '205.156.219.1', end => '205.156.219.255');
```

Which would be preferable to having to add the following 8 CIDR subnets that encapsulate that same range:

```
205.156.219.1/32
205.156.219.2/31
205.156.219.4/30
205.156.219.8/29
205.156.219.16/28
205.156.219.32/27
205.156.219.64/26
205.156.219.128/25
```

**Comment by autarch** [comment]
No, you can only add networks. However, there is a `Net::Works::Network->range_as_subnets()` method that will break a range into the biggest possible subnets for you.

**Comment by coderholic** [comment]
I see some references to `range_as_subnets` in the tests, but it's not clear how I'd actually add a network range to the tree. Can you share something that's equivalent to this example (taken from your readme) for the range `205.156.219.1 - 205.156.219.255`:

```
my $network
    = Net::Works::Network->new_from_string( string => '8.23.0.0/16' );

$tree->insert_network(
    $network,
    {
        color => 'blue',
        dogs  => [ 'Fido', 'Ms. Pretty Paws' ],
        size  => 42,
    },
);
```

**Comment by oschwald** [comment]
Something like:

```
for my $network (Net::Works::Network->range_as_subnets('205.156.219.1', '205.156.219.255', 4) {
    $tree->insert_network(
        $network,
        {
            color => 'blue',
            dogs  => [ 'Fido', 'Ms. Pretty Paws' ],
            size  => 42,
         },
    );
}
```
where the '4' in `range_as_subnets` is the IP version of your database.

**Comment by coderholic** [comment]
I've just realized that this won't necessarily work, because the order that the networks are added matters (see https://github.com/maxmind/MaxMind-DB-Writer-perl/issues/18). Therefore it seems that if I've got a dataset that consists of `start ip, end ip, data...` (which is exactly what maxmind's own downloadable CSV datasets contain) I'd need to do the following:

 1. convert it to `cidr block, data...` (and there would likely be multiple rows for each row in the input)
 1. sort based on block size
 1. add the records to a tree, as in the given examples

Is that accurate?

**Comment by oschwald** [comment]
You would only need to do this if there are overlapping ranges and you always want the smallest CIDR block to win (which isn't obviously right in this context). Last in wins.

MaxMind's GeoIP2 CSVs use CIDR notation.

**Comment by coderholic** [comment]
Great point about not needing to do this if there aren't any overlapping ranges.

When there are overlapping ranges (eg. a routing table) I thought you would always want the smallest CIDR to win (eg. http://en.wikipedia.org/wiki/Longest_prefix_match), which is why the existing "last wins" behavior caught me by surprise. When wouldn't you want that?

**Comment by oschwald** [comment]
It really depends on why you have overlapping ranges and the particulars of your data. We have many use cases internally where we do not want the smallest block to win, e.g., a data correction with a CIDR block bigger than the smallest block.

**Comment by coderholic** [comment]
OK good to know, thanks!
