### ISSUE TITLE
How to support both IPv4 and IPv6 inside the same MMDB file?

### ISSUE THREAD

**Issue by thias** [maxmind/MaxMind-DB-Writer-perl#44]
Hi,

The current example contains the following : 
```perl
my $tree = MaxMind::DB::Writer::Tree->new(
    ip_version            => 6,
    record_size           => 24,
    database_type         => 'My-IP-Data',
    languages             => ['en'],
    description           => { en => 'My database of IP data' },
    map_key_type_callback => sub { $types{ $_[0] } },
);

my $network
    = Net::Works::Network->new_from_string( string => '8.23.0.0/16' );

$tree->insert_network(
    $network,
    {
        color => 'blue',
        dogs  => [ 'Fido', 'Ms. Pretty Paws' ],
        size  => 42,
    },
);
```
This doesn't seem to work, as it tries to add an IPv4 network into an `ip_version => 6` tree.

What is the proper and working way to create a single MMDB file which would work for both IPv4 and IPv6 address lookups (like the official GeoIP2 files from MaxMind)? Should the example also be fixed? Writing two different trees to the same file, one 4 and one 6, doesn't seem to work.

**Comment by autarch** [comment]
You need to make an IPv6 version of the IPv4 network:

    my $network = Net::Works::Network->new_from_string( string => '::8.23.0.0/112' );

You could also write the network as `::817:0/112'`

I'd suggest also setting the `alias_ipv6_to_ipv4` argument to a true value when creating the true. That will cause lookups for things like `::ffff:817:0` to find the correct IPv4 address.

**Comment by lisaens** [comment]
This question has not been answered well and the example is still as it was. I'd still like to know what ip_version really means and if ipv4 and ipv6 addresses have to go into separate trees and mmdb files.

**Comment by oschwald** [comment]
The example as written now works. It is no longer necessary to map an IPv4 address to an IPv6 address manually when inserting it into an IPv6 database.

The `ip_version` attribute essentially specifies the search tree depth, 32 bits for 4 and 128 bits for 6.

When you specify an `ip_version` of 6, the writer will store IPv4 addresses at `::/96`. The database readers know to look here for IPv4 lookups. The resulting database will support both IPv6 and IPv4 addresses.

You can see the [database specification](https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md) for more details.
