### ISSUE TITLE
Should calculate the search tree record size automatically

### ISSUE THREAD

**Issue by oschwald** [maxmind/MaxMind-DB-Writer-perl#48]
There's no reason not to do this, and picking too small a size causes the build to fail. The calculation should be based on the number of nodes in the search tree + 16 (data section separator) + the sum of the length of all unique data items, or something like that.

**Comment by ratatine** [comment]
Is this perhaps why I'm getting an error building a DB saying "Node value of 16777232 exceeds the record size of 24 bits at /usr/local/lib64/perl5/MaxMind/DB/Writer/Tree.pm line 291"?

I'm currently just taking in the existing DB and iterating through it using iterate_search_tree, making a few small additions and then writing it out. I see this is a very old issue bug it sounds related? Thanks!

**Comment by oschwald** [comment]
@ratatine, you need to set a larger `record_size` in the constructor for `MaxMind::DB::Writer::Tree`. I would suggest trying `28`. It sounds like you are currently using `24`, which is the smallest record size.

This feature suggesting is related in that, if implemented, it would automatically select the appropriate record size after all of the data has been added to the database.

**Comment by ratatine** [comment]
Indeed. I will experiment and would offer a voice of support on the enhancement. I quite overtly overlooked that! Thanks.

**Comment by oschwald** [comment]
Although I still think this is how it _should_ behave, it seems unlikely that we will ever do this. I am closing this issue.
