### ISSUE TITLE
Bad IP interpreting in insert_network()

### ISSUE THREAD

**Issue by avhitrov** [maxmind/MaxMind-DB-Writer-perl#51]
OS: FreeBSD 9.3
Perl: revision 5 version 16 subversion 3
MaxMind::DB::Writer is successfully built from ports.
MaxMind::DB::Writer version 0.100004 (also tried 0.100005)
Net::Works::Network version 0.21

During test script evaluation i'm getting an error:

Bad IP address: 2001:db8:: - Invalid value for hints

It happens somewhere inside insert_network method

**Comment by oschwald** [comment]
Would you be able to provide code that reproduces the issue?

**Comment by avhitrov** [comment]
Здравствуйте, Gregory.

Вы писали 16 декабря 2015 г., 17:58:27:

> Would you be able to provide code that reproduces the issue?
> —
> Reply to this email directly or view it on GitHub.

For a first time i've got this error on this code:

#!/usr/bin/perl

use strict;
use warnings "all";
use locale;
use utf8;
use Data::Dumper;

use MaxMind::DB::Writer::Tree;
use Net::Works::Network;
use Net::CIDR;

my %types = (
        cc      => 'utf8_string',
        lat     => 'utf8_string',
        lon     => 'utf8_string',
        geo     => ['array', 'utf8_string'],
        id      => 'uint16',
);

my $tree = MaxMind::DB::Writer::Tree->new(
        ip_version              => 4,
        record_size             => 32,
        database_type           => 'My-IP-Data',
        languages               => ['ru','en'],
        description             => { en => 'My database of IP data', 'ru' => 'БД тест' },
        map_key_type_callback   => sub { $types{ $_[0] } },
);

my %GEO;
open GEO, "cities.txt";
while (<GEO>) {
        my $str = $_;
        $str =~ s/\n$//;
        my ($id, $name, $region, $county, $lat, $lon) = split /\t/, $str;
        my $code = 'RUC-'.($county =~ /^([\S]+)\ / ? $1 : $county).'-'.$region.'-'.$name;
        $GEO{$id} = { id => $id, name => $name, region => $region, county => $county, lat => $lat, lon => $lon, code => $code };
        print Dumper $GEO{$id};
}
close GEO;

open IPS, "cidr_optim.txt";
while (<IPS>) {
        s/\n$//;
        my ($first, $last, $range, $cc, $id) = split /\t/;
        next    if $id =~ /\D/;
        my (@ipaddr, @subnets);
        if ( $range =~ /(\d+\.\d+\.\d+\.\d+) - (\d+\.\d+\.\d+\.\d+)/ ) {
                @ipaddr = Net::CIDR::range2cidr "$1-$2";
                print "Range: [$1-$2] - ";
                @subnets = Net::Works::Network->range_as_subnets( $1, $2 );
                print Dumper \@subnets;
                unless ( @ipaddr ) {
                        print "Can't interpret range [$range]\n";
                }
        } else {
                print "Wrong field [range]: $range\n";
        }
        my $GEO = $id =~ /^\d+$/ && exists $GEO{$id} ? $GEO{$id} : undef;
        foreach my $network ( @subnets ) {
                print "Try $network [".$GEO->{name}."]\n";
                $tree->insert_network(
                        $network,
                        {
                                cc      => $cc,
                                geo     => ref $GEO ? [$GEO->{county}, $GEO->{region}, $GEO->{name}] : [],
                                lat     => ref $GEO ? $GEO->{lat} : '',
                                lon     => ref $GEO ? $GEO->{lon} : '',
                                id      => ref $GEO ? $id : 0,
                        },
                );
                exit(0);
        }
}
close IPS;

open my $dbh, '>:raw', './nic-ip-data.mmdb';
$tree->write_tree($dbh);


IP data files are taken from http://ipgeobase.ru/Help.html#35

But after I've got the same trouble on sample code from documentation.
So I think that the problem is covered somewhere in dependancies. I
couldn't find nor "Bad IP address" nor "Invalid value for hints"
strings in MaxMind::DB::Writer lib sources.

I can give you access to the host where the problem was discovered.


-- 
С уважением,
Андрей Хитров                          mailto:ahitrov@rambler-co.ru
Руководитель группы спецпроектов
Rambler Digital Solutions

**Comment by oschwald** [comment]
I think those errors are coming from [here](https://github.com/maxmind/MaxMind-DB-Writer-perl/blob/66e457242b35ac4738b1ec12e6c8030fb6009a9c/c/tree.c#L288). The invalid value for hints suggests we are passing a flag not available in your version of the function. Despite our misleading message, I don't think the error has anything to do with the IP address beyond it being IPv6, where we use a different set of flags.

**Comment by avhitrov** [comment]
Здравствуйте, Gregory.

Вы писали 17 декабря 2015 г., 17:58:57:

> I think those errors are coming from here. The invalid value for
> hints suggests we are passing a flag not available in your version
> of the function. Despite our misleading message, I don't think the
> error has anything to do with the IP address beyond it being IPv6,
> where we use a different set of flags.

So what can I do in order to overcome the problem?

> —
> Reply to this email directly or view it on GitHub.
>   
>      



-- 
С уважением,
Андрей Хитров                          mailto:ahitrov@rambler-co.ru
Руководитель группы спецпроектов
Rambler Digital Solutions

**Comment by oschwald** [comment]
Without digging through man pages, I suspect the issue is with the `AI_V4MAPPED` flag. You could try removing the `| AI_V4MAPPED` to see if it works. If that works, we'd need to not pass that flag on FreeBSD.
