### ISSUE TITLE
Travis fails with dev perl

### ISSUE THREAD

**Issue by autarch** [maxmind/MaxMind-DB-Writer-perl#76]
https://travis-ci.org/maxmind/MaxMind-DB-Writer-perl/jobs/138159325

It seems to not be installing all the prereqs for some mysterious reason.

**Comment by autarch** [comment]
Looks to be a Sereal problem - https://github.com/Sereal/Sereal/issues/138

**Comment by oschwald** [comment]
This was fixed long ago in Sereal. Closing.
