### ISSUE TITLE
How to convert large database?

### ISSUE THREAD

**Issue by und3f** [maxmind/MaxMind-DB-Writer-perl#78]
Hello,
I need to convert really large database (17M records) to the mmdb2 format. At a moment I run out of memory as the whole Tree not able to be placed in the memory. Are there a way to separate to smaller Trees and than merge them into one whole?

**Comment by oschwald** [comment]
There isn't a way to merge trees. 17 million records isn't particularly large. How much memory do you have? What does the data that you are inserting look like?

**Comment by und3f** [comment]
~22Gb or RAM is available. I was able to convert this database before it get bigger. Last mmdb database is 1.3Gb

Data structure: 
```
{
    "city": 
      "Mountain View" <utf8_string>
    "country_code": 
      "US" <utf8_string>
    "country_name": 
      "United States" <utf8_string>
    "ip_range": 
      "2607:f8b0:4004::-2607:f8b0:400b:ffff:ffff:ffff:ffff:ffff" <utf8_string>
    "isp": 
      "Google Inc." <utf8_string>
    "latitude": 
      "37.4229" <utf8_string>
    "longitude": 
      "-122.085" <utf8_string>
    "organization": 
      "Google Inc." <utf8_string>
    "stateprov": 
      "California" <utf8_string>
    "time_zone": 
      "America/Los_Angeles" <utf8_string>
  }
```

**Comment by oschwald** [comment]
I suspect `ip_range` is causing a lot of the bloat as it prevents the map from being reused for multiple ranges. Is this the range that you are inserting? If so, it should be possible to recover this directly from the database rather than inserting it as data in the record, although only a couple of APIs support doing this currently.

**Comment by oschwald** [comment]
Did you have any luck working around this?

**Comment by und3f** [comment]
Hello, sorry for a delay in reply. I split ranges to multiple CIDR subnetworks to organize them by masklen. So I am unable to recover this information from the database as there are multiple small CIDR subnetworks related to same IP range.
I fixed the issue by using the server with much more RAM amount.
