### ISSUE TITLE
Converting CSV into MMDB

### ISSUE THREAD

**Issue by Jaggia** [maxmind/MaxMind-DB-Writer-perl#85]
I am trying to convert the CSV files from the MaxMind website (http://dev.maxmind.com/geoip/geoip2/geolite2/) into an MMDB format. 

However, whenever my files is larger than ~10,000 lines, I always get an error like this: 

```
Argument "" isn't numeric in pack at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 389.
Cannot store an undef as data at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 93.
	MaxMind::DB::Writer::Serializer::store_data('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'utf8_string', undef, undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 355
	MaxMind::DB::Writer::Serializer::_encode_map('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'HASH(0xb2a2e60)', undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 211
	MaxMind::DB::Writer::Serializer::_store_data('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'map', 'HASH(0xb2a2e60)', undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 120
	MaxMind::DB::Writer::Serializer::store_data('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'map', 'HASH(0xb2a2e60)', undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 355
	MaxMind::DB::Writer::Serializer::_encode_map('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'HASH(0xb2b2478)', undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 211
	MaxMind::DB::Writer::Serializer::_store_data('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'map', 'HASH(0xb2b2478)', undef) called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 120
	MaxMind::DB::Writer::Serializer::store_data('MaxMind::DB::Writer::Serializer=HASH(0x3afe060)', 'map', 'HASH(0xb2b2478)', undef, 'MfnaF9bHUODrHFghs4kNT8R8Aqo') called at /usr/local/lib64/perl5/MaxMind/DB/Writer/Tree.pm line 292
	MaxMind::DB::Writer::Tree::write_tree('MaxMind::DB::Writer::Tree=HASH(0x3006fe8)', 'GLOB(0x28aa338)') called at csvReaderWriter.pl line 148
```

where "csvReaderWriter.pl" is my file on my local machine. 

I have tried running this on a server with 192GB of RAM so I don't think it is a memory issue. 
Is there anything you think that might be causing this? 

Thank You

**Comment by oschwald** [comment]
It appears that you are trying to insert an `undef` as a `utf8_string`. This will not work.

**Comment by Jaggia** [comment]
I understand that. However, I am simply converting the CSV on MaxMind's website into an MMDB and that doesn't work. Are there undef's in that CSV?

**Comment by oschwald** [comment]
There may be empty columns. It is hard for me to say what is going on without more information, but it sounds like a bug in the script.

**Comment by Jaggia** [comment]
[csvReaderWriter.txt](https://github.com/maxmind/MaxMind-DB-Writer-perl/files/790625/csvReaderWriter.txt)

I have attached my script. Please let me know what it might be.

**Comment by oschwald** [comment]
Although we would be happy to look at a small test case that demonstrates an issue, we aren't able to debug the script for you. I'd suggest asking on a coding forum or IRC for help. I am closing this as I don't think there is a bug in the API based on what has been provides.
