### ISSUE TITLE
how to merge in private addresses? (ie 10/8)

### ISSUE THREAD

**Issue by jhaar** [maxmind/MaxMind-DB-Writer-perl#86]
Hi there

I want to merge our internally gathered 10/8 GeoIP data into mmdb so that our SIEM can use GeoIP to show the location of not only Internet events - but intranet ones too

I'm no programmer, but I have managed to get a script together to do this - but it's barfing with

The IP address you provided (10.3.123.0) is not a public IP address when calling GeoIP2::Database::Reader::city on GeoIP2::Database::Reader

I see there's a "if ( is_private_ipv4($ip) || is_private_ipv6($ip) ) {" in GeoIP2/Database/Reader.pm, but I cannot figure out how to disable that "is_private_ipv4" check? Is that possible?

Thanks

**Comment by oschwald** [comment]
If you are creating your own database, I'd suggest using `MaxMind::DB::Reader` directly rather than the `GeoIP2` modules, which make assumptions about the content of the database.
