### ISSUE TITLE
Serializer incorrectly assumes the data inserted by insert_network is a hashref

### ISSUE THREAD

**Issue by oschwald** [maxmind/MaxMind-DB-Writer-perl#9]
It should support any data type listed in the spec. When inserting a string:

```
Can't use string ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"...) as a HASH ref while "strict refs" in use at /home/greg/MaxMind/MaxMind-DB-Writer-perl/.build/qNyNbaw8X8/blib/lib/MaxMind/DB/Writer/Serializer.pm line 336.
```

**Comment by jjatria** [comment]
I was assigned this module for this month's CPAN PRC, and I took a look at this issue. I had a bit of trouble getting to test things, but I think this might already be resolved.
At least making a call to `$tree->insert_network( $network, 'foo' )` from `eg/freeze-thaw` did not result in the error reported.

**Comment by oschwald** [comment]
It looks like this still happens. The error doesn't bubble up until the database is written, e.g.:

```perl
use strict;
use warnings;

use MaxMind::DB::Writer::Tree;

my $tree = MaxMind::DB::Writer::Tree->new(
    ip_version            => 6,
    record_size           => 24,
    database_type         => 'Test',
    languages             => ['en'],
    description           => { en => 'test' },
    map_key_type_callback => sub { 'utf8_string' },
);

$tree->insert_network(
    '8.8.8.0/24',
    'foo'
);

open my $fh, '>:raw', '/tmp/t.mmdb';

$tree->write_tree($fh);
```

Without looking into it, I would guess that this is non-trivial to solve. I suspect a lot of the C code assumes that the top level is a hash.

**Comment by oschwald** [comment]
After 5 years of this being open, I realized that this is actually an invalid issue. You can set `root_data_type` to a particular type and it will work. This does mean that the writer will not support mixed root data types, but that doesn't seem like a particularly useful feature anyway. I am closing this.
