### ISSUE TITLE
MaxMind::DB::Writer Merge data in Ip ranges

### ISSUE THREAD

**Issue by thevirus20** [maxmind/MaxMind-DB-Writer-perl#93]
I have a perl script that generates the mmdb files with the ip ranges without any issue for simple data.
I am using mysql to fetch a set of data from database.
What I want is now to have for e.g. something like this.
```
data -> ip start -> ip end
123 -> 0.0.0.0 -> 5.5.5.5
321 -> 1.1.1.1 -> 5.5.5.5 
```
Current Code:
```
my %types = (
    data => 'utf8_string',
);
Runs in a loop of data
$tree->insert_range(
  $row[1],$row[2],
  {
   data => $row[0],#data gets override here, 
   #$row is current row returned from db containing data as given above 
   },
 );
```

So the created mmdb lets say, should read data 123 for ip 0.0.0.0 and 123,321 for ip 5.5.5.5
Is it possible to add/append data to existing key, tried using **recurse** as merge strategy but it didn't worked, I get only data 321 for ip 5.5.5.5

Can anyone help me on this to include/add/append data to existing keys?

**Comment by oschwald** [comment]
The merging only happens at the level of data structures. A value that is not a map or an array will be overwritten rather than merged.

**Comment by thevirus20** [comment]
So changing type to array will do, well It didn't work with array either.
```
my %types = (
    data => [ 'array', 'utf8_string' ],
);
Runs in a loop of data
$tree->insert_range(
  $row[1],$row[2],
  {
   data => [$row[0]],
   },
 );
```
Can you please show how to properly push value to array type?

**Comment by thevirus20** [comment]
Any comment on how to achieve this?

**Comment by oschwald** [comment]
The merging does not append to the array; it merges or overwrites as the same position. I believe there is an example in the documentation of this exact case.

**Comment by thevirus20** [comment]
There is example of map's  different key getting merge into single block, but I need that in different way.
Can't I get the data the way I want as per the example in first post?

Can this be possible with some change in the source code?Where to change, I tried changing the 
`Tree.pm`  but it is calling another function `$self->_insert_range()`, How/where can I change this method to override the replacement of array value to push to array.

Please let me know will I be able to achieve what I want, have been doing this since days but not getting a proper way and still confused if this can be done or not.

**Comment by blaazetech** [comment]
@thevirus20 Any luck with your issue? am also trying to solve the same problem, am having multiple values to store into the array, but its just overwriting.

**Comment by thevirus20** [comment]
> @thevirus20 Any luck with your issue? am also trying to solve the same problem, am having multiple values to store into the array, but its just overwriting.

No.
