### ISSUE TITLE
Can't find appropriate typing for hashes with mixed data

### ISSUE THREAD

**Issue by ratatine** [maxmind/MaxMind-DB-Writer-perl#98]
I'm having some difficulty with the strict type mapping. The maxmind databases come with a set of data which contains multiple sub-types under a hash. For example:
      subdivisions => [
        geoname_id => 5037779,
        iso_code => "MN",
        names => {
          en => "Minnesota",
        },
      ],

The documentation at https://metacpan.org/pod/MaxMind::DB::Writer::Tree#DATA-TYPES only indicates a flat structure so if you set something to be a type "['array', 'map']" and then have any data in that array that is not a hash, it throws:
Can't use string ("5037779") as a HASH ref while "strict refs" in use at /usr/local/lib64/perl5/MaxMind/DB/Writer/Serializer.pm line 343.

In this case, this is how the data is structured coming from maxmind directly. Is there a syntax for dealing with subtypes that is not clear to me from the documentation or is this a limit to the writer? Thank you to whoever might have an idea here.

**Comment by oschwald** [comment]
The data types are on the key name. In the example you give, you should have it return `utf8_string` for the `geoname_id` key. It doesn't rely on the larger structure, just the given key within the curent hash.

**Comment by ratatine** [comment]
Thanks but this is the complete mapping I'm using. If I change subdivisions to an array of strings, everything it turned into a string with the names referenced as "HASH(0x3c73050)" and if I set it to an array of type map then it errors on the geoname_id not being set to a hash. As for the hash description shown, I get that randomly as well so I'm clearly not understanding the strict type mapping unfortunately.

my %types = (
    registered_country   => 'map',
    names                => 'map',
    city                 => 'map',
    continent            => 'map',
    country              => [ 'array', 'map' ],
    location             => 'map',
    postal               => 'map',
    traits               => 'map',

    en                   => 'utf8_string',
    de                   => 'utf8_string',
    es                   => 'utf8_string',
    fr                   => 'utf8_string',
    ja                   => 'utf8_string',
    'pt-BR'              => 'utf8_string',
    ru                   => 'utf8_string',
    'zh-CN'              => 'utf8_string',

    locales              => [ 'array', 'utf8_string' ],
    code                 => 'utf8_string',
    geoname_id           => 'uint32',
    ip_address           => 'utf8_string',
    subdivisions         => [ 'array' , 'map' ],
    iso_code             => 'utf8_string',
    country              => 'utf8_string',
    environments         => [ 'array', 'utf8_string' ],
    expires              => 'uint32',
    name                 => 'utf8_string',
    time_zone            => 'utf8_string',
    accuracy_radius      => 'uint32',
    latitude             => 'float',
    longitude            => 'float',
    metro_code           => 'uint32',
    time_zone            => 'utf8_string',
);

**Comment by oschwald** [comment]
Oh, I just looked more closely at the data structure you posted above. I think you want a hash within your `subdivisions` array. Currently, it is an array of (mostly) scalars as the hash is missing.

**Comment by ratatine** [comment]
Oh there we go. So:
subdivisions => [ {
geoname_id => 5037779,
iso_code => "MN",
names => {
en => "Minnesota",
},
} ],

Thanks. Even my third grade teacher wasn't this strict. ;)

**Comment by jrespeto** [comment]
Also having some difficulty with the strict type mapping. Trying to do a hash of hash I guessing and having issues with the map_key_type_callback. 

What im trying to get it to look like. 
```
{
   "country":{  
      "iso_code":"CN",
      "names":{  
         "en":"China",
        }
   }
}
```

What I am getting. 
```
{
    asn           64920,
    city          {
        name   "MIAMI"
    },
    company       "ASDF",
    continent     {
        code    "NA",
        names   "HASH(0x7fe2416ecee8)"
    },
    country       {
        iso_code   "US",
        names      "HASH(0x7fe240baff18)"
    }
}
```

Call back I am using. 
```
    map_key_type_callback => sub {
        my $key = shift;
        return $types{$key};
    },
```
